### ISSUE TITLE
Inconsistent display of constructor arguments between python and typescript references

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#117]
The `Python` and `TypeScript` experience differ when displaying the information needed to initialize a construct/class. 

In Python, the initializer looks like so:

<img width="401" alt="Screen Shot 2021-06-20 at 6 38 01 PM" src="https://user-images.githubusercontent.com/1428812/122680200-c9a31400-d1f6-11eb-8540-628b501f79ca.png">

Note that all properties needed to initialize `AwsAuth` are directly displayed in the initializer section. 

In TypeScript, the same initializer looks like:

<img width="577" alt="Screen Shot 2021-06-20 at 6 36 30 PM" src="https://user-images.githubusercontent.com/1428812/122680256-f6efc200-d1f6-11eb-9930-1eb03a97c3b6.png">

Note that instead of the `cluster` argument, it displays `AwsAuthProps`. 

This is a direct consequence of the fact that in python, structs are flattened out into their individual properties. This means that a typescript user has to click on `AwsAuthProps` to understand which properties need to be passed into the initializer. 

While this is technically accurate, it creates an inconsistent experience, and is actually a downgrade from the typescript API reference we currently have for `@aws-cdk/*` packages, where a table of properties is displayed immediately in the initializer level, without the extra hop. 

<img width="723" alt="Screen Shot 2021-06-20 at 6 44 42 PM" src="https://user-images.githubusercontent.com/1428812/122680396-99a84080-d1f7-11eb-8b7c-38e6ad978d1f.png">

**Comment by Chriscbr** [comment]
Keep
