### ISSUE TITLE
Display npm registry link + license link in the package meta data section

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#148]
Under github link, please make sure to add links to npm registry + license.

**Comment by gabewomble** [comment]
@RomainMuller @iliapolo I'm no longer seeing the registry information on the `metadata.json` or `assembly.json`, so this portion of functionality is currently blocked as far as I can tell

**Comment by iliapolo** [comment]
@gabewomble Noted, I will add it. Let us know which key you expect it under?

**Comment by gabewomble** [comment]
I believe it was under a `links.npm` key. IMO placing it in the same path as before will be the best option as we will likely want to add more links in the future

**Comment by gabewomble** [comment]
@iliapolo This is the typing I would like to use - `links` is optional for now to account for backfill

```ts
interface Metadata {
  date: string;
  links?: {
    npm: string;
  };
}
```
