### ISSUE TITLE
add npm registry link to the package page

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#182]
We should display the npm registry link in addition to github link.

**Comment by eladb** [comment]
We should display a link to all package managers, not just npm

**Comment by gabewomble** [comment]
The support for npm is added on the front-end, though it is dependent on the data being present on the assembly metadata (which I don't believe has been implemented yet). We can add the other registries on the client, but this is still dependent on data being present in the metadata

**Comment by gabewomble** [comment]
Fixed by #194
