### ISSUE TITLE
Maven instructions in README appear as blank box

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#214]
Reproduce: https://constructs.dev/packages/aws-lambda-golang/v/0.1.1?lang=typescript

**Comment by gabewomble** [comment]
This may be a bug with docgen - if you inspect the markdown source, the maven code sample is empty
```
In .NET: ```sh dotnet add package rwilinski.GolangFunction --version 0.1.0 ```
In Python using Pip: ```sh pip install rwilinski.aws-lambda-golang ```
In Java using Maven: ```sh ```
### Usage In Typescript:
```ts import * as golang from 'aws-lambda-golang'; ... new golang.GolangFunction(this, 'my-handler');```
```

**Comment by iliapolo** [comment]
This is a problem with the original README: https://github.com/RafalWilinski/aws-lambda-golang-cdk/tree/v0.1.1

Looks like it was already [fixed](https://github.com/RafalWilinski/aws-lambda-golang-cdk/commit/5587c12ab11d78dd3e45fcecfc777f617ec90342#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) but there hasn't been a new version yet.
