### ISSUE TITLE
Mobile - Sample code's text doesn't fit to the mobile screen

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#215]
Check out the sample code under initializer. It looks as if the sample code box is empty but actually you need to scroll right.  

https://constructs.dev/packages/aws-lambda-golang/v/0.1.1?lang=python#amazon-lambda-golang-construct

**Comment by gabewomble** [comment]
This is an issue w/ docgen formatting & should not be fixed on the client
