### ISSUE TITLE
Add coming soon label to the supported programming languages which we don't support

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#227]
We should better demonstrate that we are actively working to add support for .NET, Java and Go for the Construct Hub. 

Let's discuss about the concrete implementation.

**Comment by eladb** [comment]
We should make sure that we have a clear distinction in the UI between languages that are not supported by the Construct Hub and languages that are not supported by the library (and either supported/not-supported by the hub).
