### ISSUE TITLE
Add indication on the website that this is Dev Preview

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#238]
We need to indicate to users that this is Dev Preview version of the website.

Perhaps Chakra has built-in UI component for that?

**Comment by iliapolo** [comment]
@addihorowitz Should the indication be always visible? Or is an "About" modal enough? I was thinking to also add the explicit version of the webapp and construct-hub that is currently deployed (mainly for us).

**Comment by gabewomble** [comment]
I believe we could make a dismiss-able banner under the header for this. Our current header / nav design doesn't really allow for a fixed banner without making adjustments to the layout of it
