### ISSUE TITLE
Write "How to publish a construct"

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#244]
We will add this page in the construct hub.
The goal:
1. Explain developers how to create a construct, including references to best practices docs, design guidelines, youtube links, blog posts and any information that can help. 
2. Explain how to help their construct shine in the construct hub. For example: their code samples should compile (need to make sure to add imports etc.), they should add comments and code samples in their code to have a developer-friendly API reference, they should enable support for multiple programming languages (and we will generate the API reference and transiliate the code samples for them)
3. They should have a developer-friendly informative README file.

**Comment by eladb** [comment]
Started to work on this [here](https://gist.github.com/eladb/6c68f5af1722245f8e62084349957468)

**Comment by addihorowitz** [comment]
@eladb What's the status of this task? (I looked at the link you provided, saw some progress has been done but in high level - where do we stand?)
