### ISSUE TITLE
If Python documentation doesn't exist, the Python button should be disabled with tooltip for "documentation coming soon"

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#245]

**Comment by gabewomble** [comment]
Based on team discussions, I do not believe this is a viable solution. To do this with the current package info the client has access to, we would need to fetch documentation for each language on a given package page, which is inconsiderate to user bandwidth & connection speed.

This also won't account for:
1. Users navigating directly to the Python doc page i.e any link for a package with `?lang=python`
2. Displaying Python as an available language in the search results - this would require fetching _every single doc file_

**Comment by iliapolo** [comment]
@addihorowitz As we decided, the current behavior is:

- If python isn't supported by the package - the python button won't exist
- If python docs are missing (wether because unsupported of failure to generate) - we show an error.

I think we can close this out for now, right?
