### ISSUE TITLE
Image is not displayed on the package page

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#253]
https://constructs.dev/packages/@cloudcomponents/cdk-github-webhook/v/1.38.0?lang=typescript

Logo is not displayed only the image file name.

**Comment by gabewomble** [comment]
Currently blocked by CSP, may be fixed by an unrelated CSP fix @RomainMuller made: https://github.com/cdklabs/construct-hub/pull/223

**Comment by Chriscbr** [comment]
The image appears for me in Firefox, but not in Chrome or Safari. 🤔

**Comment by eladb** [comment]
@iliapolo looks like you fixed this, right?

**Comment by iliapolo** [comment]
@eladb I dont think this was related to my fix because the logo doesn't use a relative image

**Comment by iliapolo** [comment]
Its probably more around the CSP headers as mentioned, looks like its working now...

**Comment by gabewomble** [comment]
This is working now

![Screen Shot 2021-07-26 at 8 53 52 AM](https://user-images.githubusercontent.com/8749859/127000554-b71e3bc0-78a0-4037-be92-abb97f569882.png)
