### ISSUE TITLE
Our Architecture Diagrams are not being displayed

### ISSUE THREAD

**Issue by biffgaut** [cdklabs/construct-hub-webapp#290]
Our [NPM registry entries](https://www.npmjs.com/package/@aws-solutions-constructs/aws-apigateway-sqs/v/1.114.0) include an architecture diagram like other constructs in the hub.

But our [Construct Hub entries](https://constructs.dev/packages/@aws-solutions-constructs/aws-apigateway-sqs/v/1.114.0?lang=typescript) don't display the diagram.

Is there some setting we are missing that will cause our diagrams to be imported?

Thanks

**Comment by MrArnoldPalmer** [comment]
Looks like an issue with the conversion to absolute urls https://github.com/cdklabs/construct-hub-webapp/blob/main/src/components/Markdown/Markdown.tsx#L96

Will check this out.

**Comment by MrArnoldPalmer** [comment]
Keep
