### ISSUE TITLE
Redirect http:// to https:// - Chrome tells me constructs.dev is not secure

### ISSUE THREAD

**Issue by eladb** [cdklabs/construct-hub-webapp#301]
If users hit http://constructs.dev they need to be redirected to https://constructs.dev

![Screen Shot 2021-07-30 at 20 57 57](https://user-images.githubusercontent.com/598796/127693487-b538f0da-54e0-4053-ae20-1153e5509a7e.png)
![Screen Shot 2021-07-30 at 21 03 02](https://user-images.githubusercontent.com/598796/127693919-750fdf87-2851-4cfa-b83b-390b909a95c2.png)

**Comment by Chriscbr** [comment]
I'm unable to reproduce this on Chrome/Firefox/Safari, and on multiple different devices - I always get redirected to HTTPS pages. I'm wonder why this is? (maybe some difference from default browser settings, etc.)
