### ISSUE TITLE
Titles are cropped

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#311]
We got this issue from a user:
"long construct titles are cropped, making it hard to discover them"

https://github.com/construct-catalog/catalog/issues/155

**Comment by eladb** [comment]
@addihorowitz you should be able to transfer issues across repos. No need to duplicate

**Comment by gabewomble** [comment]
We can probably probably limit the catalog titles to two lines and truncate if it still exceeds that limit (unlikely)

**Comment by gabewomble** [comment]
Also I believe this is the same issue as #302, so we can track these together
