### ISSUE TITLE
Package page - multiple warning messages on the console

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#314]
These errors seem to be related to the integration with Adobe Analytics

**Comment by addihorowitz** [comment]
![image](https://user-images.githubusercontent.com/11254819/128182967-8f2d99b1-4693-4788-aa6c-8420842e3d42.png)

**Comment by gabewomble** [comment]
These are all warnings, not errors so nothing is breaking. Additionally, this on the owners of the analytics library to set the sameSite attribute with secure, we do not control this

**Comment by addihorowitz** [comment]
Do they know they need to set it?

**Comment by gabewomble** [comment]
This is likely a wontfix from the analytics team at this time - they've explained this is only a warning present on Firefox due to stricter tracking settings and won't be present on other browsers. Doesn't impact functionality
