### ISSUE TITLE
Add slack/twitter link preview metadata

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/construct-hub-webapp#317]
Add metadata to rendered HTML pages so that link previews for package pages linked in Slack or Twitter (e.g. by https://twitter.com/awscdkio/ ) will include the package name and package description, instead of just the usual website title and tagline.

Relevant links:
- https://api.slack.com/reference/messaging/link-unfurling#classic_unfurl
- https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary

**Comment by gabewomble** [comment]
This is a great suggestion! We haven't reached the stage of SEO / meta refinement yet, but it would be nice to tackle some simple scenarios like this to improve the general sharing experience
