### ISSUE TITLE
Add list of class properties and methods for quick navigation

### ISSUE THREAD

**Issue by alexpulver** [cdklabs/construct-hub-webapp#319]
I frequently look up class properties and methods when working with constructs. Having the list on the right side in AWS CDK API Reference allows me to quickly understand what is available. This is very important because I don't want to read the whole documentation page to find what I need, a property or method name is often enough. Then I can quickly jump to the documentation of that property or method.

AWS CDK API Reference | Construct Hub
-- | --
![image](https://user-images.githubusercontent.com/4362270/128484856-d0d0799b-485f-46ab-9f4a-4a8e7d70108f.png) | ![image](https://user-images.githubusercontent.com/4362270/128484899-8256b4df-1efb-4189-b946-a6c9af270119.png)

**Comment by eladb** [comment]
Yes this is definitely missing

**Comment by gabewomble** [comment]
This is a really solid feature suggestion. We're working on restructuring the documentation format from markdown to JSON to provide more flexibility in how we render & organize package docs, which should make this feature a possibility as well 🙂

**Comment by alexpulver** [comment]
@eladb @gabewomble pinging you to avoid the issue be closed automatically.
