### ISSUE TITLE
"constructs.dev doesn't work with ad block - loads blank page."

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#321]
Report on the community slack channel:

"Seems to be this: https://a0.awsstatic.com/s_code/js/3.0/awshome_s_code.js"

**Comment by addihorowitz** [comment]
![image](https://user-images.githubusercontent.com/11254819/128626844-bb8ffdd9-e57b-4b25-87e8-c64ddf90ea30.png)
![image](https://user-images.githubusercontent.com/11254819/128626848-92c44ca9-d17a-4fe2-968b-ea5d5e7b003f.png)

**Comment by gabewomble** [comment]
Would it be possible to get information on which browser & adblock is being used? I've tried Firefox & Chrome with Adblock Plus and uBlock Origin but haven't been able to repro

**Comment by moltar** [comment]
I use uBlock Origin on Firefox. You also might need to install additional block lists. The name of the list is on the screenshot.

**Comment by moltar** [comment]
And I confirm that it works now
