### ISSUE TITLE
Construct page header takes too much space

### ISSUE THREAD

**Issue by alexpulver** [cdklabs/construct-hub-webapp#330]
When I look for information about a construct, I am less interested in metadata. The metadata could be a single line perhaps. Then more of the documentation would be visible without scrolling

![image](https://user-images.githubusercontent.com/4362270/128972258-a3ca527f-8526-4713-bb70-b61ef8616e69.png)

**Comment by gabewomble** [comment]
I think our sentiment is that the current design of the heading area in general needs some love. It indeed takes up a fair amount of space, and doesn't yet have enough information for the space to be properly used. We're currently revisiting the usability of our UX & UI and this will be one of the areas of focus
