### ISSUE TITLE
Missing repository on Github for halloumi-ami-pipelines

### ISSUE THREAD

**Issue by badfun** [cdklabs/construct-hub-webapp#348]
The repository for [this package](https://constructs.dev/packages/halloumi-ami-pipelines/v/0.0.28?lang=typescript) is missing. Link needs to be updated or package removed (the repository is no longer under that user either).

**Comment by addihorowitz** [comment]
Thank you for reporting this issue. The repository link we display is taken from the package that the publisher publishes. We should discuss how to handle packages with broken repository links.. perhaps they should be filtered. WDYT?

**Comment by eladb** [comment]
Sounds like a broken link. I don't think there's anything we should/can do about it besides suggesting to ping the publisher so they can update their metadata.

**Comment by addihorowitz** [comment]
BTW, it doesn't seem like a broken link but more as a repository that was removed or changed to private. Check out: https://github.com/orgs/sentiampc/repositories.

**Comment by badfun** [comment]
Ok great. Closing this then.
