### ISSUE TITLE
"install" button is disabled for some packages

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#369]
For example:

https://constructs.dev/packages/@softchef/cdk-schedule-function/v/0.0.55?lang=python

**Comment by Chriscbr** [comment]
For me it shows that this package does not support Python, and the button says "Unsupported" - which I think is expected behavior. Does this still happen if you clear your cache?

**Comment by gabewomble** [comment]
+1 @Chriscbr this is expected behavior when a user hits a url with a language that isn't supported. I think we can close this as it's not a bug, is that ok @addihorowitz?
