### ISSUE TITLE
Feature request: Add package contents to the sidebar

### ISSUE THREAD

**Issue by gshpychka** [cdklabs/construct-hub-webapp#388]
The official docs have a sidebar that displays the package contents (construct props, properties and methods), making it easy to navigate within the package. It is pictured on the right here:
![image](https://user-images.githubusercontent.com/23005347/133040254-584fa707-cff3-4fff-8b5a-9e7fadc7eae7.png)

The lack of this in the Construct hub makes navigation inside a package very inconvenient and slow - I can't get an overview of available methods, and I have to scroll to get anywhere.

**Comment by gshpychka** [comment]
@gabewomble just checking - do you guys have any opinions on this? Is something like this in the works? Currently this is a dealbreaker for me, along with the lack of a quick-access list of official packages.

**Comment by gabewomble** [comment]
Hey, @gshpychka! We've got plans to convert our docs to a JSON based format which will allow the UI to implement features like this. (Currently the UI only receives a markdown file which gives very little flexibility)

**Comment by gshpychka** [comment]
Still relevant

**Comment by gshpychka** [comment]
Never mind, this has been implemented. Thanks!

**Comment by gshpychka** [comment]
Oops, I actually managed to forget what I was asking for here. This is not implemented, I apologize for the confusion.

**Comment by gshpychka** [comment]
Closed in error.

**Comment by gshpychka** [comment]
Still relevant

**Comment by gshpychka** [comment]
I see this has been released, thanks!
