### ISSUE TITLE
Feature request: descriptive page titles

### ISSUE THREAD

**Issue by gshpychka** [cdklabs/construct-hub-webapp#390]
As it is right now, all pages are titled "Construct Hub", making it hard to navigate the browsing history. 

Having more descriptive page titles would help with this a lot.

**Comment by gabewomble** [comment]
Closing as this is a duplicate of https://github.com/cdklabs/construct-hub-webapp/issues/368. I've opened a PR (https://github.com/cdklabs/construct-hub-webapp/pull/392) that will address this 🙂
