### ISSUE TITLE
Very slow page loading times

### ISSUE THREAD

**Issue by gshpychka** [cdklabs/construct-hub-webapp#391]
Package pages take more than 15 seconds to load for me.

The initial package overview block loads acceptably fast, with the rest taking a long time.

Here's an example: https://constructs.dev/packages/@aws-cdk/aws-lambda/v/1.122.0 takes over 17s to load:

![image](https://user-images.githubusercontent.com/23005347/133066934-741a689d-f6ce-44c1-9041-1ea5a6f29e0d.png)

**Comment by MrArnoldPalmer** [comment]
So we have a number of plans related to performance.

1. Switching the output of the backend from .md to json files. There is significant client side CPU time rendering large api reference documents in markdown using ReactMarkdown. In experiments, passing a json document and iterating through that ourselves performs better and gives the client more control over the layout of the api reference without requiring backfills.

2. [Migrating to NextJS SSR/SSG](https://github.com/cdklabs/construct-hub-webapp/pull/312). This would cut down on data sent over the wire and on client side computation. What remains is to figure out the best way to run this within `construct-hub` using some serverless architecture. Amplify is an option as well as existing serverless-nextjs constructs.

We aren't really dedicated to either of these right now but the plan is to implement them within the next couple months.

**Comment by MrArnoldPalmer** [comment]
@gshpychka we have broken up the rendering of readme and api reference documents to improve performance for large packages. We are tracking additional long term solutions [here](https://github.com/cdklabs/construct-hub-webapp/issues/564). I think it should be greatly improved for now though so check it out!
