### ISSUE TITLE
Long API references cannot be rendered

### ISSUE THREAD

**Issue by gshpychka** [cdklabs/construct-hub-webapp#403]
API reference could not be rendered, opening an issue as suggested on the page:

https://constructs.dev/packages/@aws-cdk/aws-ec2/v/1.122.0?lang=python#api-reference

**Comment by Chriscbr** [comment]
Thanks for reporting this. The API reference is not currently rendering because it's too large to display all at once. It looks like we need to find a long-term solution for breaking up large API references into smaller pieces so that they can be loaded by users.

Related: #287

**Comment by gabewomble** [comment]
Depends on JSON rendering, which is currently a post-GA feature

**Comment by gshpychka** [comment]
Hm, EC2 docs not rendering doesn't look like a good thing for GA.
