### ISSUE TITLE
Only part of dropdown menu is clickable

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/construct-hub-webapp#419]
<img width="256" alt="Screen Shot 2021-09-20 at 9 39 43 AM" src="https://user-images.githubusercontent.com/5008987/134040502-037a89bf-3f44-4482-8923-26b51132801f.png">

I would expect that clicking anywhere on this horizontal "FAQ" section should take me to the FAQ page since my cursor changes to the "pointer" style, but clicking does nothing unless I directly mouse over the word "FAQ". Either the entire horizontal section should be clickable (recommended) or the cursor should not change unless I am hovering over the actual link.

**Comment by gabewomble** [comment]
This should be a super quick fix, good call out!

**Comment by Chriscbr** [comment]
Fixed by https://github.com/cdklabs/construct-hub-webapp/pull/503
