### ISSUE TITLE
Package page: Add link to report an issue

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#430]
The link should redirect to the repository of the package's publisher + '/issues'. 

For example, if users want to report an issue for the construct-hub package, they will be redirected to https://github.com/cdklabs/construct-hub/issues

**Comment by gabewomble** [comment]
Should this be a P1? We already link to the repository, and this issue has a slight amount of complexity / unknown regarding handling non-github repositories. I'd lean towards making this a P2 or P3 as we still have more important feature work

**Comment by RomainMuller** [comment]
We should look to support the [bugs](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bugs) field from `package.json` as this is a far superior solution.

What this issue recommends is however a good heuristic in case that is not available.
