### ISSUE TITLE
Package Page: Improve SEO

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#431]
Make changes to the package page so that it will be found on Google Search

**Comment by gabewomble** [comment]
constructs.dev can come up in search results already. The package page currently gets a 90/100 SEO score via Lighthouse as-is. I'll see what's needed to bring the score as close to a 100

![Screen Shot 2021-09-27 at 11 02 17 AM](https://user-images.githubusercontent.com/8749859/134961231-31c85a86-6f3e-44c8-b81c-16d411b1d64e.png)
