### ISSUE TITLE
Apply Official and Community tags to relevant packages on constructs.dev

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#474]
All official packages should have the tag 'official' if they were published by the CDK type owner. These tags are all displayed as package card highlights and take users to related search results when clicked.

Please note the labels should be:
1. `AWS published (AWS CDK)`
    - For all packages with scopes `@aws-cdk`, `@aws-solutions-constructs`, `@aws-solutions-konstruck`, and `@aws-c2a`.
    - All additional packages from the aws/aws-cdk repository
2. `Hashicorp published (CDKtf)` for the cdktf packages
    - For all packages with scope `@cdktf`
    - All packages from the hashicorp/terraform-cdk repository
3. `CNCF published (CDK8s)` for the cdk8s packages
    - All packages from the cdk8s-team/cdk8s repository
4. `Community`
    - For all packages not meeting the above conditions

**Comment by gabewomble** [comment]
Depends on Tag work - should also implement a Community tag for non-official libraries
