### ISSUE TITLE
Main Header --> Getting Started

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#51]
Implement drop-down menu from the Menu Header. When the user clicks one of the items, a new tab should be opened.

Here are the links for getting started drop-down menu:
CDK
* [Quick Start by the community](https://cdkworkshop.com/)
* [Developer Guide](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html)
* [CLI](https://docs.aws.amazon.com/cdk/latest/guide/cli.html)
* [Best Practices](https://aws.amazon.com/blogs/devops/best-practices-for-developing-cloud-applications-with-aws-cdk/)
* [Community Slack Channel](https://cdk.dev/)

CDK8s
* [Getting Started](https://cdk8s.io/)

CDKtf
* [Getting Started](https://learn.hashicorp.com/tutorials/terraform/cdktf)

**Comment by BryanPan342** [comment]
Is there a base design for this? I dont mind taking a stab at this
