### ISSUE TITLE
Add keywords filter

### ISSUE THREAD

**Issue by gabewomble** [cdklabs/construct-hub-webapp#562]
To allow users to easily distinguish tags from keywords we should implement a separate "keywords" filter where values can be selected from the list or by clicking on keywords on a card or package profile

**Comment by MrArnoldPalmer** [comment]
I think we should implement a `keyword:"cdk"` type syntax for searching by keywords and/or tags. To the user tags and keywords are basically the same unless the ch operator explicitly wants to enable them as checkbox filters or highlights.

I think doing `keyword:"cdk"` would basically filter `pkg.keywords.includes('cdk') || pkg.tags.some(tag => tag.label === 'cdk')` type thing. Clicking on either a keyword, or a tag within the keyword list would do the same thing `/search?keywords=['cdk']`. Unless a tag has a `searchFilter` property, then clicking on it should `/search?tags=['tag-id']`.

**Comment by gabewomble** [comment]
I think that's an interesting proposal. The main challenge I see with this is the logic for parsing queries, but we gain the benefit of being able to create arbitrary text filters for for values that aren't displayed in the filters side panel

**Comment by gabewomble** [comment]
We currently have two options which will be discussed before taking action on this issue:

### A: Keyword search syntax

This proposal will allow users to enter a property followed by a colon and a quoted value to search by a specific field. I.E `keyword:"ec2"`. This will open the door to allowing other fields to be specifically searched, allowing more precision within our fuzzy search implementation. The primary technical challenge will be the logic regarding parsing the query

### B: Keyword filters
This proposal will allow users to see x keywords in descending order of presence as checkbox filters. To prevent a long list from taking up a massive amount of space, only a handful will initially be shown, with a "see more" button to expand the list. This implementation won't present any new technical challenges
