### ISSUE TITLE
Slow Documentation Rendering Performance

### ISSUE THREAD

**Issue by MrArnoldPalmer** [cdklabs/construct-hub-webapp#564]
Currently, rendering the readme and api reference of large packages can take a very long time, 30+ seconds in some cases. This is due to a number of factors, one being the size of assets transferred over the network, but specifically this issue focus on the time it takes to render a large markdown document using `react-markdown`.

Once the documentation markdown file is loaded, the contents are passed to the `react-markdown` library and rendered. This can cause the page to freeze for 30+ seconds while `react-markdown` parses and converts the markdown to our components, then react flushes this content to the browser and the browser renders it.

There are multiple ongoing tasks related to fixing performance:

Short term solutions:
- [x] #560

Long Term solutions:

JSON Rendering:
- [x] https://github.com/cdklabs/jsii-docgen/pull/481
- [x] [construct-hub generates json documentation format](https://github.com/cdklabs/construct-hub/issues/142)
- [ ] [construct-hub-webapp renders api reference from json documents](https://github.com/cdklabs/construct-hub-webapp/issues/171)

NextJS + SSR:
- [ ] Projen support for embedded frontends inside construct template
- [ ] Migrate construct-hub-webapp repository contents to construct-hub
- [ ] Convert frontend to nextjs application and deploy to (amplify|ECS|lambda@edge)

Related + User Reports:
- [x] #391
- [x] #403

**Comment by gshpychka** [comment]
Relevant: https://github.com/cdklabs/construct-hub-webapp/issues/391

**Comment by gabewomble** [comment]
Closing as this issue is now redundant. JSON rendering work has it's own issues we can track instead
