### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by gshpychka** [cdklabs/construct-hub-webapp#567]
The buttons to choose the CDK type on top of the search bar don't react at all for me. Nothing happens when I click on them.

The buttons I'm referring to:

![image](https://user-images.githubusercontent.com/23005347/140020495-f6430970-e644-43df-9098-619b122e124b.png)

The search itself doesn't work either - when I type my query and hit Enter, the page just refreshes, but now with a `/?` at the end of the URL.

I'm using Firefox on Linux.

**Comment by Chriscbr** [comment]
It looks like this is an outdated version of the website -- can you check if refreshing the page updates it with the latest search bar design? If that doesn't work, can you try hard refreshing (ctrl + shift + R) or clearing your browser's cache? Please let us know if either solution works.

**Comment by gabewomble** [comment]
Wow! This is an interesting bug that is definitely related to some caching troubles with the webapp we've been working on. This is a really early version of the new home page that was recently enabled. What I believe happened was

- Your browser received a new config to enable the home page
- The old webapp bundle was still cached and wasn't properly invalidated, so an early in-progress version of the new home page was rendered

**Comment by gshpychka** [comment]
I went to the page again today and now I see this:
![image](https://user-images.githubusercontent.com/23005347/140388131-a81a1bf7-d9ba-411a-b941-6f457d0434d6.png)
Search is working again. I didn't do anything to clear the cache.
