### ISSUE TITLE
When user selects tag, update copy to “Displaying *1 - 7* of *7* search results tagged *#tagname#”*

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#589]

**Comment by gabewomble** [comment]
This feature unfortunately presents a few UX gaps. If we add tags to the search details, it becomes inconsistent with other filters such as languages, cdk type, publisher, etc - which may be confusing to a user. On the flipside, if we added all possible filters to the search details, we could end up with a really messy detail line such as

`Showing 1 - 7 of 7 search results for query "foo" for CDK type "AWS CDK v1" with languages "Python", "TypeScript", publishers "AWS", "HashiCorp", "Community", and tags "Databases"`

As there's no limit to how many filters can be technically applied, I believe we should avoid working on this feature for the time being
