### ISSUE TITLE
Re-enable PWA / Service Workers for offline usage

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/construct-hub-webapp#596]
_(note: we have no current plans to work on this before GA)_

Due to issues where users are seeing outdated content and assets on the web app (#512, #567) we had to disable service workers / PWA functionality (#571). At the time of introducing these features, we were not aware of the negative impact it would have on the user experience. There were three main problems the service workers caused:

- index.html was pre-cached without unique content hashes, so that they are always served before checking the network for the latest version of index.html
- assets and data including catalog.json were cached with a "StaleWhileRevalidate" policy that only uses updated assets upon second refresh
- there was no way to updating or invalidating the existing service worker on a user's browser so that new caching logic can take effect, and no way for the website content to automatically refresh if new data is retrieved

Before we can re-introduce service workers, we should update how they cache data and how the web app can reload when new data is received. This might vary depending on what kind of data has changed (e.g. if index.html changes, we might need a different hydration mechanism compared to if catalog.json changes).

**Comment by gabewomble** [comment]
We've since brought in `react-query` which gives us a lot of the same benefits without a need to maintain the caching implementation
