### ISSUE TITLE
Package page: multiple errors on the browser's console

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#615]
Uploaded an image

**Comment by addihorowitz** [comment]
![image](https://user-images.githubusercontent.com/11254819/140739908-fde30cc9-f7d3-4b3e-8223-47c352f9661d.png)

**Comment by gabewomble** [comment]
We should be able to solve the content-security-policy issues with a BE update, but we have no control over the logging because this is an external script

**Comment by addihorowitz** [comment]
We should update the site's CSP as described in the instructions.

**Comment by gabewomble** [comment]
Issue was fixed by a CSP update
