### ISSUE TITLE
Package page: a white page and multiple errors in the browser console

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#616]
It happened when I tried to open https://constructs.dev/packages/@pahud/cdktf-aws-eks. It redirected me to: https://constructs.dev/packages/@pahud/cdktf-aws-eks/v/0.2.42?lang=dotnet and then all the errors appeared .
When I refreshed the page the page was displayed without any issues. I guess it's related to the caching problem

**Comment by addihorowitz** [comment]
![image](https://user-images.githubusercontent.com/11254819/140744601-a0b0eb26-4bbc-4e16-9ff5-2cc8db6cabb2.png)
![image](https://user-images.githubusercontent.com/11254819/140744642-87ec330c-33db-4357-b159-399bfee5b034.png)

**Comment by Chriscbr** [comment]
Not able to currently reproduce the white page issue. Some of these errors appear to be related to our analytics, and the other errors for "Invalid content type: text/html" are expected errors that we explicitly throw when documentation is not available for a given language:

https://github.com/cdklabs/construct-hub-webapp/blob/579f570fe1fe14226dd7bd4dc24d9f1bc7283c1f/src/api/package/docs.ts#L33

**Comment by Chriscbr** [comment]
Based on my understanding, the only reason this could happen is if the backend is somehow updating the catalog.json to include a version of a package before the docs have been made available - I don' think this could be a result of caching. Additional investigation needed

**Comment by gabewomble** [comment]
Going to close this as I haven't been able to repro the blank page either
