### ISSUE TITLE
White font if dark theme on Mac

### ISSUE THREAD

**Issue by flochaz** [cdklabs/construct-hub-webapp#618]
If Mac is set Dark mode font  and background are  white

![Screenshot 2021-11-08 at 17 38 42](https://user-images.githubusercontent.com/1225809/140782000-0dda5f0c-359c-4c2f-b068-8c52bd09f7ca.png)

**Comment by gabewomble** [comment]
Hey there! Looks like this bug was introduced by an automatic dependency upgrade to @chakra-ui/react 1.6.12. The issue should be fixed by https://github.com/cdklabs/construct-hub-webapp/pull/620
