### ISSUE TITLE
The github repository link should be visible by default

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#633]
Instead of hidden by default.

In addition, please bring back the npm registry link to the header. The link to npm can be hidden by default. 

These are mandatory product requirements.

**Comment by gabewomble** [comment]
I'd be hesitant to mark this as a p0 without any discussion. A focus within the new header design was to reduce how much space it took, and to do so, we decided to only show the most important information first while allowing users to see more if they chose to.

By always displaying the repository link we will need to either
- allow the header to take more space
- deprioritize downloads or author name

<img width="438" alt="Screen Shot 2021-11-09 at 2 15 39 PM" src="https://user-images.githubusercontent.com/8749859/141013686-41f1834c-df90-4417-a624-4651d1f216e9.png">
<img width="409" alt="Screen Shot 2021-11-09 at 2 15 48 PM" src="https://user-images.githubusercontent.com/8749859/141013688-3ee9dba7-1a26-4c52-83f4-bc1034120df2.png">

**Comment by addihorowitz** [comment]
@gabewomble please read the usability testing session summary. Users are looking for the GitHub links as their first action when they open a community package. Will be happy to discuss if it's still not clear.
In addition, we need to bring back the npm registry link. I'll add it to the description of this ticket. Even though we wanted that the header to take less page space, we didn't say we can remove mandatory metadata from the header.

**Comment by eladb** [comment]
Can I also suggest that we change this from `github.com` to `GitHub`. I don't see a reason to put their domain name there.

**Comment by gabewomble** [comment]
Fixed by https://github.com/cdklabs/construct-hub-webapp/pull/677
