### ISSUE TITLE
Add tags for packages so to allow them to be discovered

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#645]
Run a script that will go voer the README files of the packages, for each it will search if AWS services are mentioned there and if they are, it will add the relevant service name as a tag to this package. 
For example, if AWS Glue is mentioned the package should get a tag named 'Glue'.

All CDK8s should get the tag Kubernetes. 
We should also run the search for common utilities like: twitter, slack, Prometheus, wordpress and more. Here is a list of ops utilities we may want to create tags for https://devops.com/11-open-source-devops-tools-we-love-for-2021/.

Packages with the terms "static website" and "singular page application" and "website" should get the tags "website" and "singular page application".

Assuming that the search algorithm searches results by matching tags, it should help finding more results.

**Comment by gabewomble** [comment]
Marked as done by accident

**Comment by addihorowitz** [comment]
I created the following JSON (in the attached file) with meaningful tags we should add for packages on the hub. The JSON includes a package name and a set of tags we should add to it. I'd like to add it to our tags implementation, @valinm I'll be happy to chat with you about the best way to do that.

The goal is to allow packages to be discoverable for common use cases. For example: if someone searches for AWS services that are relevant for this package, popular technologies (like Apache, MongoDB) and common use cases like machine learning, static websites and more. 

About the implementation side:
I created this JSON by running a search on the packages' README files and it should be safe to use. I searched for the official AWS services names, some use cases and popular technologies.

In average it will add 2.5 tags per package, the highest number of tags for a specific package is 9 (for @aws-cdk/aws-apigateway). 

In total we're talking about ~1100 new tags for 434 packages that will be affected. We should think about adding this process to our backend

Here is a dict with the tag names and the number of packages that will get these tags:
{"KMS": 105, "AWS Lambda": 126, "AWS Secrets Manager": 23, "Static Website": 11, "Amazon DynamoDB": 28, "Amazon API Gateway": 137, "Slack": 19, "AWS Step Functions": 15, "Kubernetes": 35, "AWS App Mesh": 2, "AWS Cloud Development Kit (CDK)": 6, "Amazon Cognito": 19, "Amazon Elastic Container Service": 4, "AWS Fargate": 14, "AWS Backup": 3, "K8s": 3, "Amazon RDS": 3, "GitLab": 6, "Amazon Aurora": 7, "AWS IoT Core": 3, "AWS IAM": 28, "Amazon WorkMail": 2, "MongoDB": 10, "Amazon Aurora Serverless": 3, "AWS CloudFormation": 82, "Amazon EventBridge": 54, "AWS Config": 3, "AWS Systems Manager": 10, "Amazon AppStream 2.0": 1, "AWS Elemental MediaStore": 3, "Amazon EC2": 20, "Amazon Elastic Container Registry": 2, "AWS CodeBuild": 6, "AWS Key Management Service": 8, "AWS Database Migration Service": 2, "Amazon WorkSpaces": 1, "Amazon CloudWatch": 32, "AWS Security Hub": 1, "Amazon Simple Queue Service (SQS)": 1, "AWS Elastic Beanstalk": 1, "AWS Service Catalog": 5, "AWS Elemental MediaLive": 1, "AWS Global Accelerator": 2, "Amazon Kinesis": 32, "Amazon Redshift": 14, "AWS Glue": 8, "Amazon EC2 Auto Scaling": 3, "AWS Batch": 7, "AWS CodePipeline": 7, "AWS CloudTrail": 6, "AWS Auto Scaling": 2, "Apache Spark": 2, "Amazon CloudFront": 16, "Amazon Route 53": 4, "AWS Certificate Manager": 8, "Amazon Elasticsearch Service": 10, "AWS Management Console": 69, "AWS IoT Things Graph": 1, "AWS Chatbot": 3, "AWS OpsWorks": 2, "Amazon FSx for Lustre": 1, "Machine Learning": 1, "Elastic Load Balancing": 7, "AWS CodeCommit": 6, "AWS Transfer for SFTP": 1, "Amazon Textract": 1, "AWS Resource Access Manager": 1, "AWS Cloud9": 2, "Amazon Managed Streaming for Apache Kafka": 2, "Amazon Pinpoint": 4, "AWS CodeDeploy": 3, "AWS CodeStar": 1, "Amazon GuardDuty": 1, "Angular": 5, "AWS Data Pipeline": 1, "Amazon MQ": 1, "Amazon ElastiCache": 2, "AWS AppSync": 3, "AWS Direct Connect": 1, "Amazon EMR": 2, "Amazon VPC": 3, "Amazon GameLift": 1, "AWS RoboMaker": 1, "AWS WAF": 9, "AWS IoT Analytics": 1, "AWS Directory Service": 1, "Amazon Inspector": 1, "Amazon Neptune": 2, "Amazon Athena": 1, "AWS Amplify": 4, "Single Page Application": 3, "Deep Learning": 1, "AWS Cloud Map": 1, "Amazon Comprehend": 1, "AWS IoT 1-Click": 1, "AWS Budgets": 1, "AWS Shield": 3, "AWS Artifact": 1, "AWS X-Ray": 1, "Amazon Transcribe": 1, "Amazon Elastic Kubernetes Service": 1}

**Comment by addihorowitz** [comment]
<script src="https://gist.github.com/addihorowitz/06740bf7c8d170da2f36bf5d23c7cde7.js"></script>

**Comment by addihorowitz** [comment]
https://gist.github.com/addihorowitz/06740bf7c8d170da2f36bf5d23c7cde7

**Comment by gabewomble** [comment]
Closing because this work was fixed by a backend update
