### ISSUE TITLE
Clicking on items in the navigation area doesn't work

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#670]
https://constructs.dev/packages/cdk-construct-simple-nat/v/0.1.125?lang=typescript#whats-the-difference-between-ec2-nat-instancesnatinstances-and-nat-instances-created-by-this-construct

Try to click the items under the FAQ

**Comment by RomainMuller** [comment]
This appears to be due to link-in-link here, making the heading anchor not be what it's supposed to be.
