### ISSUE TITLE
performance: aws-cdk-lib takes too long to load

### ISSUE THREAD

**Issue by eladb** [cdklabs/construct-hub-webapp#691]
Is it because we are loading all submodules before we display the root module?

**Comment by eladb** [comment]
It seems like this is mostly network-bound. The UI must wait for `assembly.json` to be downloaded before it can render, and it seems like my slow network is why this is such a horrible experience.

<img width="875" alt="Screen Shot 2021-11-17 at 15 20 03" src="https://user-images.githubusercontent.com/598796/142208328-c0b1a971-3f7b-42ab-b5b7-2d666cde7954.png">

The navigation bar is rendered immediately after the docs markdown is rendered, but information about submodules is only available in the `assembly.json` file (33MiB).

@RomainMuller  @iliapolo @MrArnoldPalmer @gabewomble @Chriscbr What information do we need from  `assembly.json` anyway? Besides information about submodules, it seems like we don't really need it and it's a huge file (for `aws-cdk-lib` it is

**Comment by eladb** [comment]
OK, basically, it seems to me that a quick win could be to basically remove the `types` section from the assembly. For `aws-cdk-lib`, for example, it will reduce the size from 33.1MiB to 1.1MiB.

We can do this without much risk - when we process packages in the backend, store another file for each package (e.g. `assembly-slim.json`) without the `types` section and then change our frontend to use this file instead of `assembly.json`).

**Comment by iliapolo** [comment]
The deployment will have to be two phased here, first backend + reprocess and then front end. 

Or implement a fallback on the front end

**Comment by eladb** [comment]
OK, after going through the backend code, it seems like adding another file is going to be a bit of a project, so I am going to just delete `types` from `assembly.json` itself.

To verify this, I've patched up the webapp to delete `types` immediately after `assembly.json` is downloaded and verified that the experience is not broken, so I believe it is low risk to simply reprocess.
