### ISSUE TITLE
Improve API Reference direct URLs

### ISSUE THREAD

**Issue by RomainMuller** [cdklabs/construct-hub-webapp#714]
We should improve the URLs for API Reference entry points so that they are more reliable & less prone to collisions. The list of problems with those follows:

- They are based on the language-specific fully qualified name, so one cannot change languages once on those pages (as the name is not valid in other languages). The original Jsii FQN should be used instead.
- They are heavily sanitized (any non-alphanumerical character is removed, and it is fully down-cased), so they are ripe for collisions. The original FQN (made assembly-relative, so for example `@aws-cdk/core.Construct` would be `Construct`) can be used as-is in the URL. It'll also make URLs more readable, and easier to "manually write"

This requires coordinated changes in `jsii-docgen` (which provides data to the front-end through the markdown document), `construct-hub` (which passes a linkFormatter to `jsii-docgen`), and `construct-hub-webapp` (which has to route those URLs to the right content, and also generates these URLs again in the Nav-Tree).

**Comment by Chriscbr** [comment]
Since this requires breaking changes across multiple packages, I'm planning to address this as part of https://github.com/cdklabs/construct-hub/issues/142
