### ISSUE TITLE
Change the behavior on a language change

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#715]
Currently, if you go to this link 
https://constructs.dev/packages/constructs/v/3.3.161/api/constructsconstruct?lang=python

and change the language to Java, you get an error page.

We should make sure than whenever the link includes a reference to a header in the documentation (in this case /api/constructsconstruct and the user presses another programming language it will reload the entire page, means: the link will be https://constructs.dev/packages/constructs/v/3.3.161/?lang=java and not https://constructs.dev/packages/constructs/v/3.3.161/api/constructsconstruct?lang=java

**Comment by RomainMuller** [comment]
Related to #714
