### ISSUE TITLE
Searching for pre-defined categories from the search bar doesn't work

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#719]
Though there is a tag named "Artificial Intelligence (AI)". When I click the tag in the keywords filter it retrieves the result. Perhaps it's because the name of the tag includes '()'? 
We can just try to reprocess the tag again with a different name: 'Artificial Intelligence'

The same for "cloud services integrations". You can get relevant results if you run the search from the keywords filter but not from the search bar

**Comment by gabewomble** [comment]
This seems like an edge-case which will also be fixed by #724
