### ISSUE TITLE
document sidebar with hash prefix will be ignored

### ISSUE THREAD

**Issue by pahud** [cdklabs/construct-hub-webapp#736]
![image](https://user-images.githubusercontent.com/278432/142826604-32c3ea98-4908-47b4-8f0b-a410019553f1.png)

![image](https://user-images.githubusercontent.com/278432/142826458-138dbede-ebb6-4831-869c-7f9f0b9e4ef0.png)

**Comment by Chriscbr** [comment]
I'm going to make this as a P2 since this doesn't seem to affect too many packages. But I don't think this should be too hard to fix

**Comment by gabewomble** [comment]
Bumped to p1 as I've learned this does cause a page crash. Looks like cases of this are rare, but this definitely needs to be fixed to prevent other users from encountering the issue
