### ISSUE TITLE
Separate anchor link in API reference headers

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/construct-hub-webapp#867]
Currently, all headers on API reference pages that can be linked to are direct links. This is a small pain point since it makes it harder to copy the names of headers, which is common since they are often the names of methods and constructs that you want to use in your code.

I wonder if it might be an improvement to change the headers so they no longer link, and add a separate ornament that appears on mouseover, which either takes links to the correct anchor, or which saves a link to your clipboard to the appropriate API reference item.

Examples of this UI pattern in other docs websites:

----

(pkg.go.dev)
<img width="282" alt="Screen Shot 2022-01-13 at 2 56 03 PM" src="https://user-images.githubusercontent.com/5008987/149421865-b40a3487-5f97-4284-af6d-1df7ab20b436.png">

----

(stripe.com)
<img width="311" alt="Screen Shot 2022-01-13 at 2 58 09 PM" src="https://user-images.githubusercontent.com/5008987/149422067-9ab2792d-db5e-4336-8173-1eb2900a3006.png">

----

(developer.android.com)
<img width="294" alt="Screen Shot 2022-01-13 at 3 00 55 PM" src="https://user-images.githubusercontent.com/5008987/149422370-0ebc9eb6-aa44-4a7e-b289-7106884bb850.png">

**Comment by gabewomble** [comment]
Great idea, I think this will be a very straightforward usability improvement!
