### ISSUE TITLE
Switching package versions should not reset API reference page

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/construct-hub-webapp#869]
When you switch to a different version of a package while viewing a particular API, the user's language selection is retained (good), but they get taken back to the README page (bad). This makes it cumbersome for users to compare what APIs are available in different versions of construct libraries.

**Comment by gabewomble** [comment]
I think this is a reasonable change / fix. The only consideration that needs to be made is handling the 404 if two versions do not share the same API (either removed in a later version or doesn't exist in an older one)

**Comment by Chriscbr** [comment]
@gabewomble I'm wondering if using javascript we could make the package pages "smart" so if a link takes you to a page that exists but the particular anchor within the page does not exist (because an API was removed / didn't exist), could we detect that display some kind of mini alert/notice somewhere on the page? So e.g. if you get linked to https://constructs.dev/packages/@aws-cdk/aws-s3/v/1.139.0/api/Bucket#nonExistentProp it will tell you "hey, nonExistentProp doesn't exist".

Not sure if I've ever seen seen any websites that do this though, so maybe this would just be weird 🤷‍♂️

**Comment by gabewomble** [comment]
That would be a fun little feature, though I imagine it's more effort than it's worth 🙃 

I think for the time being we can just stick with the error messaging we already have. From my testing, this feels like an edge-case
